/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class MyLibrary {
    fun someLibraryMethod(): Boolean {
        return true
    }
    fun greet(name: String): String {
        return "Hello, $name!"
    }
}
